### ISSUE TITLE
An error occurred: PathAccessException: Creation failed, path = 'C:\Program Files\reboot_launcher\logs' (OS Error: Toegang geweigerd. , errno = 5) Stacktrace:  #0      _Directory.createSync (dart:io/directory_impl.dart:129) #1      _File.createSync (dart:io/file_impl.dart:303) #2      startServer (package:reboot_launcher/src/util/server.dart:43) <asynchronous suspension>

### ISSUE THREAD

**Issue by gamertje** [Auties00/reboot_launcher#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maozven** [comment]
open the launcher with administrator

**Comment by gamertje** [comment]
Ok


Op di 22 aug. 2023 07:50 schreef maozven ***@***.***>:

**Comment by gamertje** [comment]
I did alr


Op di 22 aug. 2023 07:50 schreef maozven ***@***.***>:
