### ISSUE TITLE
something 

### ISSUE THREAD

**Issue by kjtostizz** [Auties00/reboot_launcher#29]
when i try in launch fortnite error message comes up-     An error occurred: PathAccessException: Creation failed, path = 'C:\Program Files\reboot_launcher\logs' (OS Error: Access is denied.
, errno = 5)
Stacktrace:
 #0      _Directory.createSync (dart:io/directory_impl.dart:129)
#1      _File.createSync (dart:io/file_impl.dart:303)
#2      startServer (package:reboot_launcher/src/util/server.dart:43)
<asynchronous suspension>

**Comment by Auties00** [comment]
You are using an old launcher version, update on discord

**Comment by kjtostizz** [comment]
found out my laptop doesnt like old fortnite i tried era ,reboot, nova
