### ISSUE TITLE
i go in and it  loads for 5s and then crashes wheen i launch the game

### ISSUE THREAD

**Issue by gbhgvb** [Auties00/reboot_launcher#31]
i go in and it  loads for 5s and then crashes wheen i launch the game

**Comment by gbhgvb** [comment]
i go in and it loads for 5s and then crashes wheen i launch the game

**Comment by Fehype** [comment]
The season you're trying to play isn't supported yet. Try seeking help on the reboot's Discord.
**Stop opening multiple issues, just one is enough.**
