### ISSUE TITLE
Button Start Event not working

### ISSUE THREAD

**Issue by Juko13** [Auties00/reboot_launcher#33]
When I enter the game in Chapter 2 Season 7 and I have previously turned on the Event, I appear at the place where the Event starts and when I click start event nothing happens in my game. Is there any way I can fix this?

**Comment by Fehype** [comment]
You need to update the keychain, use this version of LawinServer in local mode: https://github.com/Milxnor/LawinServer.

**Comment by MarvelcoOGFN** [comment]
or use my backend lawin v3 i have updated keychain
