### ISSUE TITLE
cobalt.dll dll is not a valid dll

### ISSUE THREAD

**Issue by plshelpmr** [Auties00/reboot_launcher#41]
dont know how to fix

**Comment by timko0110** [comment]
how to fix that?

**Comment by plshelpmr** [comment]
yes how to fix that

**Comment by plshelpmr** [comment]
???

**Comment by pxisii** [comment]
> ???

did you ever fix it?

**Comment by milonekaaa** [comment]
pls help fix

**Comment by oleisa** [comment]
how to fix

**Comment by LokiZukunft99** [comment]
You need to delete the launcher, reinstall it with anti-cheat off and run it as an administrator

**Comment by itallianjeff** [comment]
reboot dll is not a vaild reboot
