### ISSUE TITLE
Game Instantly Crashes

### ISSUE THREAD

**Issue by FNCARL** [Auties00/reboot_launcher#44]
In 12.41 it just shows up the loading screen when you press launch fortnite and then crashes immediately, do you know how to fix this issue? (ive tried using adminstrator)

**Comment by juannic** [comment]
same

**Comment by rodrigootavarees** [comment]
When I lauch in version 14.60 my game it instantly crashes,can someone help me please?

**Comment by FR05tYZ** [comment]
when i launched both 14.60 and 10.40 when i get to the "press to start" screen the game crashes how to fix?
